apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: chatapp-ns
type: Opaque
data:
  MONGO_INITDB_ROOT_USERNAME: bW9uZ29hZG1pbg==   # mongoadmin
  MONGO_INITDB_ROOT_PASSWORD: c2VjcmV0           # secret
  MONGODB_URI: bW9uZ29kYjovL21vbmdvYWRtaW46c2VjcmV0QG1vbmdvZGI6MjcwMTcvZGJuYW1lP2F1dGhTb3VyY2U9YWRtaW4=  # mongodb://mongoadmin:secret@mongodb:27017/dbname?authSource=admin
  JWT_SECRET: ZXlKaGJHY2lPaUpJVXpJMU5pSjkuZXlSU2IybGZJakFpT0dSdGFXNGlMQ0oySWpvaUluUnN1WkZpTUNJc0ltOXlaeUk2SWpFME1UVTFOak00T0Rjd05DNDJaV0U1Ykc5M1lXNW5MbU52YlMxd2NHeHBibVV1ZDJWaWIyOXVkRzlzYjJGa1pYSmxjaTVzYVc1bklpd2libTl1WlNJNkltSmxZWFZzYkY5bGJtTmhibVZzWlY5amFYUmxJREJoYm1Rdk9EbGpNR0ZsYzNSaGJXVTZhV3hzYjNkME5EY3dOeUkxTVRNdU16ZzFZekk0TlMxa1pXeHpaU0lzSW1GcFpDSTZJbU5zWVdOcmN5NXpaWEoyYVhSbGNpNTNhWFpsY25OcGIyNDZlRFV4SWl3aWJtRnRaU0k2SWtOb1lXTnBZV3d0WVhCd2FXUmxJaXdpY0dWeWMybHZiajQ9
  PORT: NTAwMQ==